### ISSUE TITLE
Galaxy S3 Mini

### ISSUE THREAD

**Issue by mnagel** [mnagel/prismatd#105]
samsung gt-i8190
android 4.1.2

playstore: "dieser artikel ist nicht mit deinem gerät kompatibel" 
apk installation: "fehler beim parsen des pakets"

kann man da was machen?

**Comment by pkern** [comment]
Play Store sagt blöderweise nicht, woran es hakt.

Resolution	480 x 800 pixels (~233 ppi pixel density) [entspricht Galaxy S]

GLES 2 sollte es auch können.

Meine Vermutung ist inkompatibel mit Android 4.1.2 (API level 16). Wir sagen aktuell minSdkVersion 22 in build.gradle. Was dann auch zur kaputten Installation passt.
