### ISSUE TITLE
Exit könnte toller anzeigen, dass man gerade kaputtgeht

### ISSUE THREAD

**Issue by pkern** [mnagel/prismatd#111]
z.B. Health(-Bar?) in den Exit packen, Farbe ändern, Lebenszahl reinrendern

**Comment by mnagel** [comment]
Ich würde vorschlagen, statt dem o auf den Enemy die aktuelle Lebenszahl auf die Exit-Gridcell rendern und insbes. dynamisch runterzählen, wenn dann ein zweiter/dritter/... entkommt.
