### ISSUE TITLE
Überlegen, ob man Geld ins nächste Level mitnehmen können soll

### ISSUE THREAD

**Issue by pkern** [mnagel/prismatd#112]

**Comment by mnagel** [comment]
Zwischen Waves ist das ja schon so.

Zwischen Missionen ist das eine ausgesprochen "schwierige" Idee, weil erstens weiterhin nicht mal das Balancing innerhalb einer Mission steht, und zweitens dieser Vorschlag eine positive Feedback-Schleife einführt, die dafür sorgt, dass die Missionen entweder unschaffbar sein müssen, oder unvermeidbar immer stärker zu einfach werden und Balancing/Spielspaß sterben.

Wenn, dann bekommt man in der nächsten Mission weniger Geld, wenn man in der vorherigen noch was über hatte.

**Comment by pkern** [comment]
Die Frage ist halt, inwiefern man Incentives setzt eine Mission auch ohne Ausreizung des Budgets zu schaffen. Von freemium Spielen kennt man ja Sterne die man sammeln und ggf. im Notfall auch einsetzen kann.

Sterne für geschafft mit X Türmen / Y Geld / etc wären ja auch spannend. Vielleicht löst das dann schon das "Problem".
