### ISSUE TITLE
 show tower cost somewhere in the gui

### ISSUE THREAD

**Issue by mnagel** [mnagel/prismatd#19]
desc: show tower cost somewhere in the gui
type: :feature

**Comment by mnagel** [comment]
würde sich total anbieten, dass jetzt im menü über den tower drüberzurendern.
und wenn man dann dabei ist, könnte man unten zu den enemies im menü noch den text "send next wave" rendern...

**Comment by pkern** [comment]
Gefixt in f7b66a29b20fb5c649234d9a9f6d3e97ad4dcecf.
