### ISSUE TITLE
design tech tree

### ISSUE THREAD

**Issue by pkern** [mnagel/prismatd#22]

**Comment by mnagel** [comment]
* colors
* target policy
* damage type
* damage
* ...

**Comment by pkern** [comment]
3 Gegnerfarben, 3 Türme, 3 Upgrades?
150% Schaden auf Primärfarbe, 50% Schaden auf Sekundärfarbe, 100% sonst?
Wird dann halt irgendwo ein balance problem, insbesondere wenn z.B. target policy fix wäre pro Turmtyp statt dynamisch.

**Comment by mnagel** [comment]
Ich denke, hier muss noch etwas geplant und ausformuliert werden.
Sobald ich was habe, melde ich mich.

**Comment by mnagel** [comment]
Gegner haben RGB Leben
Geschosse haben RGB Schaden
Wenn Gegen R,G,B = 0,0,0 dann tot

Tower haben Level
Tower haben RGB Schaden (basiert auf Level)
Tower haben Target Policy (statisch pro Turm-Art)

Tower haben Schadensarten (RGB-Schaden, Slow, Recolor)

------------------------

Rot-Turm
Gruen-Turm
Blau-Turm
Slow-Turm
Paint-Red-Turm

------------------------

Rot-Gegner
Gruen-Gegner
Blau-Gegner

Lila-Gegner

White Monster (slow, high HP)

Fast Yellow (fast, low HP)

Rainbow Enemy (Changes Color)

-------------------------

Out of Scope / Addons
* Colorpicker-Tower
* Booster-Tower (Range, DMG, Color-Addon)
* Selektierbare Target Policy
* Mulit-Hit, Chaining, ...
* Range, Firerate per Tower-Level
