### ISSUE TITLE
Wollen wir Single Use Items?

### ISSUE THREAD

**Issue by mnagel** [mnagel/prismatd#26]

**Comment by mnagel** [comment]
Ich bin nicht der Meinung, dass sie wichtig sind für den Spielfluss,
und das wir uns dann einiges an Implementierungsaufwand sparen können.

**Comment by pkern** [comment]
Wenn man ein sinnvolles Menü hat, sind single-use items ja nicht sonderlich schwierig zu implementieren. Insbesondere falls die items global wirken würden. (Extra Leben, global mehr damage durch die Tüme, etc.) Ich denke die Frage ist primär, ob man das zum Retten vorsehen sollte wenn die Meute bereits ins Ziel einläuft. Wenn es nur zwischen den Waves wirklich möglich ist, dann kann man es vermutlich auch lassen.

**Comment by cipold** [comment]
--> Milestone 2
