### ISSUE TITLE
remove 30 fps limit in awt

### ISSUE THREAD

**Issue by mnagel** [mnagel/prismatd#39]
currently game seems to be limited to 30fps

**Comment by pkern** [comment]
I'd go the other way around and limit Android to 30fps. 60fps seems excessive for this game and takes a lot of CPU. I'd expect a real device to get quite warm when my desktop is already spinning at one full core in the emulator.

**Comment by pkern** [comment]
And unfortunately there isn't really a generic solution. https://stackoverflow.com/questions/4772693/how-to-limit-framerate-when-using-androids-glsurfaceview-rendermode-continuousl links to https://github.com/LWJGL/lwjgl/blob/master/src/java/org/lwjgl/opengl/Sync.java, which I suppose we could use for frame limiting.

**Comment by mnagel** [comment]
EXPECTED_FPS gibt es für awt.
ich würde es generell auf 60 hochsetzen und vorsehen, dass man das Limit für Benchmarking-Zwecke wegnehmen kann.

Manuell sleepen auf Android? Meinetwegen...

**Comment by pkern** [comment]
Hattest du ein konkretes Problem mit 30fps?
