### ISSUE TITLE
Sollen Türme die Route der Gegner beeinflussen?

### ISSUE THREAD

**Issue by mnagel** [mnagel/prismatd#4]

**Comment by mnagel** [comment]
Voll dagegen! Finde ich spielerisch und vom Blancing her nicht attraktiv.
Ich mag es viel lieber, wenn der Weg vorgegeben ist, und man die Türme drumrumstellen kann.

**Comment by pkern** [comment]
Muss der Weg dann kolisionsfrei sein, d.h. dürfen Türme nicht auf dem Weg liegen? Oder ist das ok, wenn die durch die Türme durchgehen?

**Comment by pkern** [comment]
Aha, siehe #5. Ja, dann wohl eher das. Aber dann wollen wir Korridore.
