### ISSUE TITLE
HP Anzeige

### ISSUE THREAD

**Issue by mnagel** [mnagel/prismatd#42]
Die Pixel sollten irgendwo eine HP-Anzeige haben (Lebensbalken, Drehgeschwindigkeit, Anzahl Ecken, Farbiger Rahmen, Brightness-Overlay, Tooltip, ...)

**Comment by pkern** [comment]
Stellt sich raus, wir machen das eigentlich schon: Life ist ein RGB-Wert (wtf?) und die Engine rendet die Enemies als Farbverlauf basierend auf dem normalized life value.

Naiv hätte ich mir mal den Lebensbalken angeschaut, aber wollen wir dann sinnigerweise drei? (R, G, B)

**Comment by pkern** [comment]
Die andere Möglichkeit, die wir hätten ist halt farbigen Schaden mit einem Scaling Factor reinzurechnen. Damit könnte man immernoch modellieren, dass eine Farbe keinen Schaden macht, wenn man will. Und dann halt im Notfall sowas wie getRedDamageFactor() auf den Tümen oder sowas.
